// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByTvSE6Ow6P96sjsKQ1dhYkSqYVDZsXpU',
    appId: '1:1013566501275:web:727b59d6021deed3c6713e',
    messagingSenderId: '1013566501275',
    projectId: 'food-portion',
    authDomain: 'food-portion.firebaseapp.com',
    storageBucket: 'food-portion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2iN-1ZhlZ6XFlMVnjgD1eJtmWVyKgIIc',
    appId: '1:1013566501275:android:ebb09e90b85c4862c6713e',
    messagingSenderId: '1013566501275',
    projectId: 'food-portion',
    storageBucket: 'food-portion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeeBl8OwDuz8OlQ9GWwoJAQd7rRnVBRw',
    appId: '1:1013566501275:ios:4bccf1986c841adac6713e',
    messagingSenderId: '1013566501275',
    projectId: 'food-portion',
    storageBucket: 'food-portion.appspot.com',
    iosClientId: '1013566501275-dg72i64kkpppsh9vpdqaivd736ij4c3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodPortion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeeBl8OwDuz8OlQ9GWwoJAQd7rRnVBRw',
    appId: '1:1013566501275:ios:4bccf1986c841adac6713e',
    messagingSenderId: '1013566501275',
    projectId: 'food-portion',
    storageBucket: 'food-portion.appspot.com',
    iosClientId: '1013566501275-dg72i64kkpppsh9vpdqaivd736ij4c3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodPortion',
  );
}
